/*
 * MATLAB Compiler: 2.1
 * Date: Sun May 25 20:21:25 2003
 * Arguments: "-B" "macro_default" "-O" "all" "-O" "fold_scalar_mxarrays:on" "-O" "fold_non_scalar_mxarrays:on" "-O" "optimize_integer_for_loops:on" "-O" "array_indexing:on" "-O" "optimize_conditionals:on" "-B" "C:\Documents and Settings\daniel\Application Data\MathWorks\MATLAB\R12\mccpath" "-I" "C:\matlabR12\toolbox\matlab\general" "-I" "C:\matlabR12\toolbox\matlab\ops" "-I" "C:\matlabR12\toolbox\matlab\lang" "-I" "C:\matlabR12\toolbox\matlab\elmat" "-I" "C:\matlabR12\toolbox\matlab\elfun" "-I" "C:\matlabR12\toolbox\matlab\specfun" "-I" "C:\matlabR12\toolbox\matlab\matfun" "-I" "C:\matlabR12\toolbox\matlab\datafun" "-I" "C:\matlabR12\toolbox\matlab\audio" "-I" "C:\matlabR12\toolbox\matlab\polyfun" "-I" "C:\matlabR12\toolbox\matlab\funfun" "-I" "C:\matlabR12\toolbox\matlab\sparfun" "-I" "C:\matlabR12\toolbox\matlab\graph2d" "-I" "C:\matlabR12\toolbox\matlab\graph3d" "-I" "C:\matlabR12\toolbox\matlab\specgraph" "-I" "C:\matlabR12\toolbox\matlab\graphics" "-I" "C:\matlabR12\toolbox\matlab\uitools" "-I" "C:\matlabR12\toolbox\matlab\strfun" "-I" "C:\matlabR12\toolbox\matlab\iofun" "-I" "C:\matlabR12\toolbox\matlab\timefun" "-I" "C:\matlabR12\toolbox\matlab\datatypes" "-I" "C:\matlabR12\toolbox\matlab\verctrl" "-I" "C:\matlabR12\toolbox\matlab\winfun" "-I" "C:\matlabR12\toolbox\matlab\demos" "-I" "C:\matlabR12\toolbox\local" "-I" "C:\matlabR12\toolbox\simulink\simulink" "-I" "C:\matlabR12\toolbox\simulink\blocks" "-I" "C:\matlabR12\toolbox\simulink\simdemos" "-I" "C:\matlabR12\toolbox\simulink\simdemos\aerospace" "-I" "C:\matlabR12\toolbox\simulink\simdemos\automotive" "-I" "C:\matlabR12\toolbox\simulink\simdemos\simfeatures" "-I" "C:\matlabR12\toolbox\simulink\simdemos\simgeneral" "-I" "C:\matlabR12\toolbox\simulink\simdemos\simnew" "-I" "C:\matlabR12\toolbox\simulink\dee" "-I" "C:\matlabR12\toolbox\stateflow\stateflow" "-I" "C:\matlabR12\toolbox\stateflow\sfdemos" "-I" "C:\matlabR12\toolbox\stateflow\coder" "-I" "C:\matlabR12\toolbox\rtw\rtw" "-I" "C:\matlabR12\toolbox\rtw\rtwdemos" "-I"
 * "C:\matlabR12\toolbox\rtw\targets\asap2\asap2" "-I" "C:\matlabR12\toolbox\rtw\targets\asap2\asap2\user" "-I" "C:\matlabR12\toolbox\rtw\accel" "-I" "C:\matlabR12\toolbox\rtw\ada" "-I" "C:\matlabR12\toolbox\cdma\cdma" "-I" "C:\matlabR12\toolbox\cdma\cdmamasks" "-I" "C:\matlabR12\toolbox\cdma\cdmamex" "-I" "C:\matlabR12\toolbox\cdma\cdmademos" "-I" "C:\matlabR12\toolbox\comm\comm" "-I" "C:\matlabR12\toolbox\comm\commdemos" "-I" "C:\matlabR12\toolbox\comm\commobsolete" "-I" "C:\matlabR12\toolbox\commblks\commblks" "-I" "C:\matlabR12\toolbox\commblks\commmasks" "-I" "C:\matlabR12\toolbox\commblks\commmex" "-I" "C:\matlabR12\toolbox\commblks\commblksdemos" "-I" "C:\matlabR12\toolbox\commblks\commblksobsolete" "-I" "C:\matlabR12\toolbox\compiler" "-I" "C:\matlabR12\toolbox\control\control" "-I" "C:\matlabR12\toolbox\control\ctrlguis" "-I" "C:\matlabR12\toolbox\control\ctrlobsolete" "-I" "C:\matlabR12\toolbox\control\ctrlutil" "-I" "C:\matlabR12\toolbox\control\ctrldemos" "-I" "C:\matlabR12\toolbox\daq\daq" "-I" "C:\matlabR12\toolbox\daq\daqdemos" "-I" "C:\matlabR12\toolbox\database\database" "-I" "C:\matlabR12\toolbox\database\dbdemos" "-I" "C:\matlabR12\toolbox\database\vqb" "-I" "C:\matlabR12\toolbox\datafeed\datafeed" "-I" "C:\matlabR12\toolbox\datafeed\dfgui" "-I" "C:\matlabR12\toolbox\dials" "-I" "C:\matlabR12\toolbox\dspblks\dspblks" "-I" "C:\matlabR12\toolbox\dspblks\dspmasks" "-I" "C:\matlabR12\toolbox\dspblks\dspmex" "-I" "C:\matlabR12\toolbox\dspblks\dspdemos" "-I" "C:\matlabR12\toolbox\dspblks\dsprtw\util_c" "-I" "C:\matlabR12\toolbox\rtw\targets\ecoder" "-I" "C:\matlabR12\toolbox\exlink" "-I" "C:\matlabR12\toolbox\filterdesign\filterdesign" "-I" "C:\matlabR12\toolbox\filterdesign\quantization" "-I" "C:\matlabR12\toolbox\filterdesign\filtdesdemos" "-I" "C:\matlabR12\toolbox\finance\finance" "-I" "C:\matlabR12\toolbox\finance\calendar" "-I" "C:\matlabR12\toolbox\finance\findemos" "-I" "C:\matlabR12\toolbox\finance\finsupport" "-I" "C:\matlabR12\toolbox\finderiv\finderiv" "-I"
 * "C:\matlabR12\toolbox\fixpoint" "-I" "C:\matlabR12\toolbox\fixpoint\fxpdemos" "-I" "C:\matlabR12\toolbox\fixpoint\obsolete" "-I" "C:\matlabR12\toolbox\ftseries\ftseries" "-I" "C:\matlabR12\toolbox\ftseries\ftsdemos" "-I" "C:\matlabR12\toolbox\ftseries\ftsdata" "-I" "C:\matlabR12\toolbox\ftseries\ftstutorials" "-I" "C:\matlabR12\toolbox\fuzzy\fuzzy" "-I" "C:\matlabR12\toolbox\fuzzy\fuzdemos" "-I" "C:\matlabR12\toolbox\garch\garch" "-I" "C:\matlabR12\toolbox\garch\garchdemos" "-I" "C:\matlabR12\toolbox\ident\ident" "-I" "C:\matlabR12\toolbox\ident\idobsolete" "-I" "C:\matlabR12\toolbox\ident\idguis" "-I" "C:\matlabR12\toolbox\ident\idutils" "-I" "C:\matlabR12\toolbox\ident\iddemos" "-I" "C:\matlabR12\toolbox\ident\idhelp" "-I" "C:\matlabR12\toolbox\images\images" "-I" "C:\matlabR12\toolbox\images\imdemos" "-I" "C:\matlabR12\toolbox\instrument\instrument" "-I" "C:\matlabR12\toolbox\instrument\instrumentdemos" "-I" "C:\matlabR12\toolbox\lmi\lmictrl" "-I" "C:\matlabR12\toolbox\lmi\lmilab" "-I" "C:\matlabR12\toolbox\map\map" "-I" "C:\matlabR12\toolbox\map\mapdisp" "-I" "C:\matlabR12\toolbox\map\mapproj" "-I" "C:\matlabR12\toolbox\simulink\mdldiff" "-I" "C:\matlabR12\toolbox\motdsp\motdsp" "-I" "C:\matlabR12\toolbox\motdsp\motdspmex" "-I" "C:\matlabR12\toolbox\motdsp\motdspasm\bin" "-I" "C:\matlabR12\toolbox\motdsp\motdspblks" "-I" "C:\matlabR12\toolbox\motdsp\motdspmasks" "-I" "C:\matlabR12\toolbox\motdsp\motdspdemos" "-I" "C:\matlabR12\toolbox\mpc\mpccmds" "-I" "C:\matlabR12\toolbox\mpc\mpcdemos" "-I" "C:\matlabR12\toolbox\mutools\commands" "-I" "C:\matlabR12\toolbox\mutools\subs" "-I" "C:\matlabR12\toolbox\ncd" "-I" "C:\matlabR12\toolbox\nnet\nnet" "-I" "C:\matlabR12\toolbox\nnet\nnutils" "-I" "C:\matlabR12\toolbox\nnet\nncontrol" "-I" "C:\matlabR12\toolbox\nnet\nndemos" "-I" "C:\matlabR12\toolbox\nnet\nnobsolete" "-I" "C:\matlabR12\toolbox\optim" "-I" "C:\matlabR12\toolbox\pde" "-I" "C:\matlabR12\toolbox\powersys\powersys" "-I" "C:\matlabR12\toolbox\powersys\powerdemo" "-I" "C:\matlabR12\toolbox\reqmgt" "-I"
 * "C:\matlabR12\toolbox\robust" "-I" "C:\matlabR12\toolbox\rptgen" "-I" "C:\matlabR12\toolbox\rptgenext" "-I" "C:\matlabR12\toolbox\sb2sl" "-I" "C:\matlabR12\toolbox\signal\signal" "-I" "C:\matlabR12\toolbox\signal\fdatoolgui" "-I" "C:\matlabR12\toolbox\signal\sptoolgui" "-I" "C:\matlabR12\toolbox\signal\sigdemos" "-I" "C:\matlabR12\toolbox\simulink\simcoverage" "-I" "C:\matlabR12\toolbox\splines" "-I" "C:\matlabR12\toolbox\stats" "-I" "C:\matlabR12\toolbox\symbolic" "-I" "C:\matlabR12\toolbox\wavelet\wavelet" "-I" "C:\matlabR12\toolbox\wavelet\wavedemo" "-I" "C:\matlabR12\toolbox\rtw\targets\xpc\xpc" "-I" "C:\matlabR12\toolbox\rtw\targets\xpc\target\build\xpcblocks" "-I" "C:\matlabR12\toolbox\rtw\targets\xpc\xpcdemos" "-I" "C:\matlabR12\toolbox\rtw\targets\xpc\target\kernel\embedded" "-I" "C:\matlabR12\work" "-I" "C:\matlabR12\daniel" "-I" "C:\matlabR12\daniel\bitoperations" "-I" "C:\matlabR12\daniel\geometria" "-L" "C" "libmmfile.mlib" "-A" "line:on" "-G" "-A" "debugline:on" "-O" "fold_scalar_mxarrays:off" "-O" "fold_non_scalar_mxarrays:off" "-O" "optimize_integer_for_loops:off" "-O" "array_indexing:off" "-O" "optimize_conditionals:off" "libmmfile.mlib" "-v" "-I" "E:\trabajos\daniel\practicasC++\conv" "-t" "-T" "codegen" "E:\trabajos\daniel\practicasC++\conv\MyFunc.m" 
 */

#ifndef MLF_V2
#define MLF_V2 1
#endif

#ifndef __MyFunc_h
#define __MyFunc_h 1

#ifdef __cplusplus
extern "C" {
#endif

#include "libmatlb.h"

extern void InitializeModule_MyFunc(void);
extern void TerminateModule_MyFunc(void);
extern _mexLocalFunctionTable _local_function_table_MyFunc;

extern mxArray * mlfMyFunc(mxArray * In1, mxArray * In2);
extern void mlxMyFunc(int nlhs, mxArray * plhs[], int nrhs, mxArray * prhs[]);

#ifdef __cplusplus
}
#endif

#endif
