#if !defined(AFX_VCDATAPOINT_H__C18A6B20_A568_4A80_9AE2_ED194A508EDF__INCLUDED_)
#define AFX_VCDATAPOINT_H__C18A6B20_A568_4A80_9AE2_ED194A508EDF__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CVcDataPointLabel;
class CVcBrush;
class CVcPen;
class CVcMarker;

/////////////////////////////////////////////////////////////////////////////
// CVcDataPoint wrapper class

class CVcDataPoint : public COleDispatchDriver
{
public:
	CVcDataPoint() {}		// Calls COleDispatchDriver default constructor
	CVcDataPoint(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CVcDataPoint(const CVcDataPoint& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CVcDataPointLabel GetDataPointLabel();
	CVcBrush GetBrush();
	CVcPen GetEdgePen();
	CVcMarker GetMarker();
	float GetOffset();
	void SetOffset(float newValue);
	void ResetCustom();
	void Select();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VCDATAPOINT_H__C18A6B20_A568_4A80_9AE2_ED194A508EDF__INCLUDED_)
