#if !defined(AFX_VCRECT_H__64EAE516_F957_473E_9CCA_8A1323E3A1AA__INCLUDED_)
#define AFX_VCRECT_H__64EAE516_F957_473E_9CCA_8A1323E3A1AA__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CVcCoor;

/////////////////////////////////////////////////////////////////////////////
// CVcRect wrapper class

class CVcRect : public COleDispatchDriver
{
public:
	CVcRect() {}		// Calls COleDispatchDriver default constructor
	CVcRect(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CVcRect(const CVcRect& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CVcCoor GetMin();
	CVcCoor GetMax();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VCRECT_H__64EAE516_F957_473E_9CCA_8A1323E3A1AA__INCLUDED_)
